name: "Generate dotenv file"
description: "Action for generating a dotenv file based on a template file"
author: "Jacob Fredericksen"
branding:
  icon: "file-plus"
  color: "red"
inputs:
  template-paths:
    description: "Filepath or space-delimited list of filepaths of the template file(s) used to generate the dotenv file"
    required: true
  output-path:
    description: "Filepath for the output file"
    required: false
    default: ".env"
  cache:
    description: "Boolean specifying whether to cache the output file ('true' or 'false')"
    required: false
    default: "true"
  key:
    description: "Key used to identify the cached/uploaded dotenv file (default: concatenation of the template paths and the GITHUB_SHA env var)"
    required: false
  upload:
    description: "Boolean specifying whether to upload the output file as an artifact ('true' or 'false')"
    required: false
    default: "false"
  allow-missing-vars:
    description: "Boolean specifying whether to generate the dotenv file even if one or more variables included in the template file is missing from the environment ('true' or 'false')"
    required: false
    default: "false"
outputs:
  key:
    description: "Key used to identify the dotenv file"
runs:
  using: "node20"
  main: "dist/index.js"
