name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: generate-dotenv
      uses: ./
      with:
        template-paths: 'tests/stubs/_.env'
    - name: Cache dotenv
      id: cache-dotenv
      uses: actions/cache@v3
      with:
        path: .env
        key: ${{ steps.generate-dotenv.outputs.key }}
        fail-on-cache-miss: true
    # - name: Require cached dotenv file
    #   if: steps.cache-dotenv.outputs.cache-hit != 'true'
    #   run: echo "Failed to restore cached dotenv file using key ${{ steps.generate-dotenv.outputs.key }}" && exit 1
